### ISSUE TITLE
Tracking issue for `variable-size-kernels`

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin#3038]
This is a tracking issue for RFC0005 `variable-size-kernels`, https://github.com/mimblewimble/grin-rfcs/pull/21

#### Steps:
* [] Introduce protocol version 2
* [] Add protocol version support (backwards compatibility)
* [] Test and ensure compatibility across node and wallet versions

#### Unresolved questions:
None so far

**Comment by lehnberg** [comment]
@antiochp feel free to edit/update as you see fit, just put something in there

**Comment by antiochp** [comment]
There's also #3010 which tracks this from the perspective of the 2.1.0 release?
