### ISSUE TITLE
tracking issue - invalid rangeproof handling (good header, bad block)

### ISSUE THREAD

**Issue by antiochp** [mimblewimble/grin#3605]
The following PRs were merged to `current/5.0.x` as part of the emergency hardfork on 20210318 - 

* https://github.com/mimblewimble/grin/pull/3598 "Removing verifier caches"
* https://github.com/mimblewimble/grin/pull/3600 "Rewind bad block"
* https://github.com/mimblewimble/grin/pull/3603 "Rewind bad headers"

Additionally the following PR was merged to `master` -

* https://github.com/mimblewimble/grin/pull/3597 "Removing verifier caches"

Some of this work was "tactical" and we do not need this on `master`.
Some of this work was "strategic" and we do want it on `master`.

This tracking issue is a central place to document what needs to be on `master` and what we can omit.
There are also some additional changes/improvements that we want to consider, off the back of the hardfork and fix.

This is a work in progress and details will be updated as we go. 
This is not time-critical but the proposed upcoming `5.1.0` release is a good candidate for cleaning this up if possible.

----

This is rough first draft of where we stand currently - 

* Currently the rangeproof verification cache is disabled on both master and 5.0.x branches.
  *  We need to decide if we want to reintroduce this fully and what the cache key impl needs to be.
  * tromp had a question about utxhohashset (fast sync state?) validation and where/how caching is involved
* "rewind bad block" should not be required on `master` as it was simply a hot fix to get past the "bad fork"
* We do want to propagate the `InvalidBlockProof` error (to ban peers correctly)
  * the whole error/bool/ban logic needs a rethink and cleanup as its hard to reason about currently
* Related #3603 (on `5.0.x` branch) "rewind headers and ban"
  * "rewind headers" also a hot fix and not required on `master`
* but we _do_ need to handle the "good header, bad block" scenario robustly somehow and this needs impl on `master`
  * one option is explicit list of "bad headers" as we have in that PR but ideally this is dynamic

 ----
 Tasks broken out as separate issues - 

- [x] https://github.com/mimblewimble/grin/issues/3606 ~"enable verifier cache (fix cache key impl)"~
  - [x] took a different approach and removed it entirely #3628 
- [x] https://github.com/mimblewimble/grin/issues/3607 "good header, bad block"
- [x] https://github.com/mimblewimble/grin/issues/3627 error/bool/ban logic cleanup

**Comment by trevyn** [comment]
Question: I understand that there is a lot of work that will go into fully resolving this in the way that we would like. Given that the network has settled a bit, what is the minimal set that would allow an "acceptable" release from master now? Is the already-applied "Removing verifier caches" enough, or do we also strictly need "good header, bad block" and/or changes to the error/bool/ban logic?

**Comment by tromp** [comment]
This time we only needed to rewind less than a day back, but it would be good to prepare for a possible future need to rewind beyond the 1 week horizon. Perhaps that can rely on the existence of block archive nodes.

**Comment by antiochp** [comment]
Closing this issue - all PRs are merged and prepped for an initial `5.1.0`.
