### ISSUE TITLE
Tracking issue for deprecation of `failure` crate

### ISSUE THREAD

**Issue by trevyn** [mimblewimble/grin#3631]
Per its [README](https://github.com/rust-lang-nursery/failure#readme), the `failure` crate is deprecated:

>**Notice**: `failure` is deprecated. If you liked `failure`'s API, consider using:
>- [Anyhow](https://github.com/dtolnay/anyhow) is a good replacement for `failure::Error`.
>- [thiserror](https://github.com/dtolnay/thiserror) is a good, near drop-in replacement for `#[derive(Fail)]`.

I agree with the suggestion to migrate to `anyhow` and `thiserror`, and will investigate it unless anyone has other suggestions or objections.

Investigating on branch https://github.com/trevyn/grin/tree/trevyn-deprecate-failure. To do:

- [x] Wait for https://github.com/mimblewimble/grin/pull/3630 or equivalent to be merged; it contains code that interacts with [failure's Error/ErrorKind pattern](https://rust-lang-nursery.github.io/failure/error-errorkind.html) that needs to be reworked.
- [x] Rework `#[derive(Fail)]` to `#[derive(thiserror::Error)]`
- [x] Try removing `Error`/`ErrorKind` pattern — is this still required with `thiserror`?

**Comment by antiochp** [comment]
I'm :+1: on exploring replacements for `failure` here. We have had multiple iterations of our error handling, none of which have felt 100% right.
And we are definitely not the only rust project to struggle with this.

**Comment by trevyn** [comment]
PR in progress: #3633
