### ISSUE TITLE
Cherry-pickers' club: Coordinating commits between master and testnet

### ISSUE THREAD

**Issue by sesam** [mimblewimble/grin#472]
General issue to track & discuss cherry-picking master and testnet branches

**Comment by sesam** [comment]
commits in master I've not yet processed:
[ ] cc9ec53 sync_head port from testnet1 (#425)
[ ]442ef3b port across "simple_sync" changes from testnet1 branch (#409)
[ ] (2/2 deprecated?) 77eac16 Locator fix master (#381)
[ ] (1/2 deprecated?) c6b94dd generate locator heights all the way down to 0 by powers of 2 (#378)

Prioritised to merge (#468 conflict sources):
[ ] e57cfe2 Name all threads
[ ] c6b94dd generate locator heights, halving all the way to 0
[ ] bac0291 Ping heights (407)
and maybe more

**Comment by antiochp** [comment]
#425 and #409 should be fine - they are porting stuff back to master from testnet1.
#378 I believe is fine also (same stuff should be on both branches ad was part of the simple_sync)

**Comment by sesam** [comment]
# Commits in milestone/testnet1 which I can't figure out myself yet:
- [ ] ?? df34fe6 add debug logging to GetBlock handling
- [ ] TODO 9945371 Fix locator response on the wrong chain
- [ ] ?? 15b61c4 Update BlockHeaderInfo Struct (#419)
- [ ] TODO e57cfe2 Name all threads

 - @ignopeverell on top of your mind, do we need these 3?
   - [ ] b7fcf0b Same as DuplicateCommitment fixes, for kernels
   - [ ] acd7519 Fix DuplicateCommitment, with a pony on top
   - [ ] ?? 431a5b8 Fix `DuplicateCommitment` check

 - sync & buddy stuff, or applies to code isn't in master (or maybe already was deprecated?)
   - [ ] f5b42dc [testnet1] sync head & improved fork handling (#413)
   - [ ] 031c43e Fix p2p tests (p2p/tests/peer_handshake)
   - [ ] 86dd82d Cleanup direct refs to peer map or peer store
   - [ ] 36a1cef Partial simple sync from @antiochp, with sync flag
   - [ ] 6fcb787 Use current height instead of 0 for new buddy locator
   - [ ] (dep?) eb152e6 Fix crash when no header were sent (bhs.length>0 check)
   - [ ] 50d9fa4 first pass on better peer affinity (#388)
   - [ ] (dep?) 898a727 Extend block locator length \# p2p:types MAX_LOCATORS=14, from 10

**Comment by yeastplume** [comment]
This list isn't being maintained and is very out of date... closing.
